" Filetype plugins duhhhhh
filetype plugin on

" Mouse support
set mouse=a

" Wrapping
set nowrap
set display=lastline
set breakindent
set breakindentopt=shift:3,sbr

" UI
set number		" show line numbers
hi LineNr ctermbg=234
hi CursorLineNr ctermbg=234
set cursorline		" highlight current line
set cursorlineopt=number,screenline
set showmatch		" highlight matching [{()}]

" Searching
set incsearch		" search as characters are entered
set hlsearch		" highlight matches

" Movement
"" move via visual line
nnoremap j gj
vnoremap j gj

nnoremap k gk
vnoremap k gk

nnoremap <Down> gj
vnoremap <Down> gj
inoremap <Down> <C-o>gj

nnoremap <Up> gk
vnoremap <Up> gk
inoremap <Up> <C-o>gk

nnoremap 0 g0
nnoremap $ g$

" Airline
let g:airline_powerline_fonts = 1
let g:airline_theme='base16color'

" ALE
nmap <silent> <C-j> :ALENext<cr>
nmap <silent> <C-k> :ALEPrevious<cr>

" Folding
set foldenable		" enable folding
set foldlevelstart=10	" open most folds by default
set foldnestmax=10	" 10 nested fold max
set foldmethod=indent	" fold based on indent level
set foldcolumn=0
hi Folded ctermbg=235
hi FoldColumn ctermbg=233

" Filetype specifics
autocmd BufRead,BufNewFile *.txt,*.tex,*.md setlocal wrap linebreak spell
autocmd BufRead,BufNewFile *.txt,*.tex,*.md nunmap $

autocmd BufRead,BufNewFile *.go setlocal shiftwidth=4 tabstop=4

" Disable ALE Linters I don't like
" let g:ale_linters_ignore = {'html': ['proselint']}

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
